### ISSUE TITLE
JS (buildArea.html) - add table functionality. Append parts and prices.

### ISSUE THREAD

**Issue by ikyle53** [It-s-not-a-bug-it-s-a-feature/EZ-PC-Shopper#41]
Table will appear below the 6 images on build.html.

**Comment by nojronatron** [comment]
Scott drove, Jon navigated for a bit.

**Comment by nojronatron** [comment]
Elizabeth drove, Jon navigated for a bit.

**Comment by nojronatron** [comment]
Final testing in process. Closing issue as goal achieved.
